dist: xenial

language: python

install:
    - pip install -r requirements_dev.txt

script:
    - cd tests && pytest -v

jobs:
    include:
        - stage: Test
          python: "3.7"
        - python: "3.6"
        - python: "3.5"
        - python: "3.4"
        - python: "2.7"
        - stage: Lint
          python: "3.7"
          script: flake8

notifications:
    email: false
