dist: xenial

language: python

python:
    - 3.7
    - 3.6
    - 3.5
    - 3.4
    - 2.7

install:
    - pip install -r requirements_dev.txt

script:
    - cd tests && pytest -v

notifications:
    email: false
