dist: xenial

language: python

python:
    - 3.7
    - 3.6
    - 3.5
    - 2.7

install:
    - pip install tox tox-travis

script:
    - tox

matrix:
    include:
        - env: TOXENV=lint3
        - env: TOXENV=lint2

notifications:
    email: false
